name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Cleanup Disk Space
        run: |
          echo "Freeing up disk space..."
          rm -rf ~/.m2/repository
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
